"""Compare an article-like vertical temperature profile with this Python model.

The article figure gives a temperature map, not raw data.  This script reads
digitized profiles produced by ``digitize_article_temperature_profiles.py`` and
compares them with the instantaneous pulse-end temperature from the heat-source
model:

    F(r) = 2 E / (pi w^2) * exp(-2 r^2 / w^2)
    q(r, z) = (1 - R) * alpha * F(r) * exp(-alpha_eff * z)

Here ``w`` is the 1/e^2 fluence radius.  This is the same normalisation used
by ``gst_model.py`` and integrates to the pulse energy ``E``.  The printed
Eq. (5) in the article appears to miss the radial factor of two, while Fig. 4a
is consistent with the 1/e^2 convention.

The goal is diagnostic: estimate whether the plotted depth decay is consistent
with the effective absorption coefficient used in the thermal model.

By default it also propagates the temperature field for a few nanoseconds and
plots delayed center-line profiles.  This is useful if the article image is not
the strictly instantaneous Eq. (5) distribution, but a profile after early
thermal diffusion and latent-heat redistribution.
"""

from __future__ import annotations

import argparse
from dataclasses import replace
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np

from gst_model import AxisymmetricThermalModel, GST225, Grid, LaserPulse, Substrate
from plot_utils import savefig_overwrite


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--energy-nj", type=float, default=650)
    parser.add_argument("--beam-radius-um", type=float, default=30.0)
    parser.add_argument("--film-nm", type=float, default=230.0)
    parser.add_argument("--ambient-k", type=float, default=300.0)
    parser.add_argument("--alpha-linear-um", type=float, default=16.2)
    parser.add_argument("--alpha-eff-um", type=float, default=16.2)
    parser.add_argument(
        "--fit-alpha-eff",
        action="store_true",
        help="also fit alpha_eff to article points by least squares",
    )
    parser.add_argument(
        "--no-phase-change",
        action="store_true",
        help="compare model pulse-end temperature without latent heat",
    )
    parser.add_argument(
        "--times-ns",
        type=str,
        default="0,1,5",
        help=(
            "comma-separated delays after the pulse to plot from the heat equation; "
            "0 means pulse-end temperature"
        ),
    )
    parser.add_argument(
        "--cooling-dt-ns",
        type=float,
        default=0.1,
        help="time step for short post-pulse diffusion calculation",
    )
    parser.add_argument(
        "--lateral-z-nm",
        type=float,
        default=45.0,
        help="GST depth for the lateral T(r) comparison",
    )
    parser.add_argument(
        "--radial-extent-um",
        type=float,
        default=60.0,
        help="radial domain used for the lateral diagnostic calculation",
    )
    parser.add_argument(
        "--dr-um",
        type=float,
        default=1.0,
        help="radial grid step for the lateral diagnostic calculation",
    )
    parser.add_argument(
        "--plot-r-step-um",
        type=float,
        default=0.25,
        help="smooth plotting step for calculated lateral curves; does not change the solver grid",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("output/article_temperature_profile_comparison.png"),
    )
    parser.add_argument(
        "--csv",
        type=Path,
        default=Path("output/article_temperature_profile_comparison.csv"),
    )
    parser.add_argument(
        "--article-csv",
        type=Path,
        default=Path("output/digitized_article_temperature/vertical_centerline_from_image.csv"),
        help=(
            "CSV/TXT with columns z_nm,T_K. By default uses the corrected "
            "profile generated by digitize_article_temperature_profiles.py"
        ),
    )
    parser.add_argument(
        "--article-lateral-csv",
        type=Path,
        default=Path("output/digitized_article_temperature/lateral_surface_from_image.csv"),
        help=(
            "CSV/TXT with columns r_um,T_K for the right panel. By default uses "
            "the corrected profile generated by digitize_article_temperature_profiles.py"
        ),
    )
    parser.add_argument(
        "--article-corrected-temperature-column",
        type=str,
        default="T_corrected_K",
        help="corrected article-temperature column to read from digitized article CSV files",
    )
    parser.add_argument(
        "--article-raw-temperature-column",
        type=str,
        default="T_raw_median_K",
        help="raw article-temperature column to read from digitized article CSV files",
    )
    return parser.parse_args()


def parse_times_ns(text: str) -> list[float]:
    times = [float(part.strip()) for part in text.split(",") if part.strip()]
    if not times:
        times = [0.0]
    if min(times) < 0.0:
        raise SystemExit("--times-ns must contain non-negative values")
    return sorted(set(times))


def incident_peak_fluence(energy_j: float, beam_radius_m: float) -> float:
    """Gaussian peak fluence F0 [J/m^2] for exp(-2 r^2 / w^2).

    ``beam_radius_m`` is the 1/e^2 fluence radius.  The integral of
    ``F0 * exp(-2 r^2 / w^2)`` over the transverse plane is ``energy_j``.
    """
    return 2.0 * energy_j / (np.pi * beam_radius_m**2)


def eq5_temperature(
    z_m: np.ndarray,
    *,
    gst: GST225,
    pulse: LaserPulse,
    ambient_k: float,
    alpha_eff_1_per_m: float,
) -> np.ndarray:
    """Eq. (5) pulse-end temperature ignoring latent heat and diffusion."""
    f0 = incident_peak_fluence(pulse.energy, pulse.radius_1e2)
    deposited = (
        (1.0 - gst.reflectivity)
        * gst.alpha_linear
        * f0
        * np.exp(-alpha_eff_1_per_m * z_m)
    )
    return ambient_k + deposited / (gst.density * gst.specific_heat)


def eq5_lateral_temperature(
    r_m: np.ndarray,
    *,
    z_m: float,
    gst: GST225,
    pulse: LaserPulse,
    ambient_k: float,
    alpha_eff_1_per_m: float,
) -> np.ndarray:
    """Eq. (5) lateral profile at a fixed depth, no latent heat/diffusion."""
    f_r = incident_peak_fluence(pulse.energy, pulse.radius_1e2) * np.exp(
        -2.0 * r_m**2 / pulse.radius_1e2**2
    )
    deposited = (
        (1.0 - gst.reflectivity)
        * gst.alpha_linear
        * f_r
        * np.exp(-alpha_eff_1_per_m * z_m)
    )
    return ambient_k + deposited / (gst.density * gst.specific_heat)


def model_centerline_temperature_profiles(
    z_m: np.ndarray,
    times_ns: list[float],
    *,
    gst: GST225,
    pulse: LaserPulse,
    film_thickness_m: float,
    ambient_k: float,
    include_phase_change: bool,
    dt_ns: float,
) -> dict[float, np.ndarray]:
    """Interpolate model center-line profiles at requested post-pulse delays."""
    grid = Grid(
        film_thickness=film_thickness_m,
        radial_extent=2.0e-6,
        dr=0.5e-6,
        dz_film=2.0e-9,
        dz_substrate=20.0e-9,
    )
    model = AxisymmetricThermalModel(
        gst=gst,
        substrate=Substrate.silica(thickness=0.3e-6),
        pulse=pulse,
        grid=grid,
        ambient_temperature=ambient_k,
        include_phase_change=include_phase_change,
    )
    max_time_ns = max(times_ns)
    if max_time_ns == 0.0:
        temperature = model.pulse_end_temperature()
        center = temperature[model.film_rows, 0]
        return {0.0: np.interp(z_m, model.z[model.film_rows], center)}

    result = model.simulate_cooling(
        end_time=max_time_ns * 1e-9,
        time_step=dt_ns * 1e-9,
        save_every=1,
        progress=False,
    )
    profiles: dict[float, np.ndarray] = {}
    z_model = result.z[result.film_mask]
    for time_ns in times_ns:
        it = int(np.argmin(np.abs(result.time - time_ns * 1e-9)))
        center = result.temperature[it, result.film_mask, 0]
        profiles[time_ns] = np.interp(z_m, z_model, center)
    return profiles


def model_lateral_temperature_profiles(
    r_signed_m: np.ndarray,
    times_ns: list[float],
    *,
    z_m: float,
    gst: GST225,
    pulse: LaserPulse,
    film_thickness_m: float,
    ambient_k: float,
    include_phase_change: bool,
    dt_ns: float,
    radial_extent_m: float,
    dr_m: float,
) -> dict[float, np.ndarray]:
    """Interpolate model lateral profiles at fixed z for signed r values."""
    grid = Grid(
        film_thickness=film_thickness_m,
        radial_extent=radial_extent_m,
        dr=dr_m,
        dz_film=2.0e-9,
        dz_substrate=20.0e-9,
    )
    model = AxisymmetricThermalModel(
        gst=gst,
        substrate=Substrate.silica(thickness=0.3e-6),
        pulse=pulse,
        grid=grid,
        ambient_temperature=ambient_k,
        include_phase_change=include_phase_change,
    )
    max_time_ns = max(times_ns)
    if max_time_ns == 0.0:
        times = np.array([0.0])
        temperatures = model.pulse_end_temperature()[None, :, :]
    else:
        result = model.simulate_cooling(
            end_time=max_time_ns * 1e-9,
            time_step=dt_ns * 1e-9,
            save_every=1,
            progress=False,
        )
        times = result.time
        temperatures = result.temperature

    abs_r = np.abs(r_signed_m)
    profiles: dict[float, np.ndarray] = {}
    for time_ns in times_ns:
        it = int(np.argmin(np.abs(times - time_ns * 1e-9)))
        # First interpolate each radial column in z, then interpolate in r.
        radial_at_z = np.array(
            [
                np.interp(z_m, model.z[model.film_rows], temperatures[it, model.film_rows, ir])
                for ir in range(model.nr)
            ]
        )
        profiles[time_ns] = np.interp(abs_r, model.r, radial_at_z)
    return profiles


def fit_alpha_eff_um(
    z_m: np.ndarray,
    t_article: np.ndarray,
    *,
    gst: GST225,
    pulse: LaserPulse,
    ambient_k: float,
) -> float:
    """Fit alpha_eff in Eq. (5), keeping all other parameters fixed."""
    try:
        from scipy.optimize import minimize_scalar
    except ImportError as exc:  # pragma: no cover - only if scipy is missing.
        raise SystemExit("scipy is required for --fit-alpha-eff") from exc

    def loss(alpha_eff_um: float) -> float:
        predicted = eq5_temperature(
            z_m,
            gst=gst,
            pulse=pulse,
            ambient_k=ambient_k,
            alpha_eff_1_per_m=alpha_eff_um * 1e6,
        )
        return float(np.mean((predicted - t_article) ** 2))

    result = minimize_scalar(loss, bounds=(0.5, 30.0), method="bounded")
    return float(result.x)


def local_alpha_eff_estimates_um(
    z_m: np.ndarray,
    t_article: np.ndarray,
    *,
    ambient_k: float,
) -> np.ndarray:
    """Point-by-point alpha_eff from T(z)/T(0); z=0 is undefined."""
    estimates = np.full_like(z_m, np.nan, dtype=float)
    delta0 = t_article[0] - ambient_k
    valid = (z_m > 0.0) & (t_article > ambient_k) & (delta0 > 0.0)
    estimates[valid] = -np.log((t_article[valid] - ambient_k) / delta0) / z_m[valid] / 1e6
    return estimates


def write_csv(
    path: Path,
    z_nm: np.ndarray,
    t_article: np.ndarray,
    t_eq5: np.ndarray,
    t_model: np.ndarray,
    local_alpha_um: np.ndarray,
) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    data = np.column_stack(
        [z_nm, t_article, t_eq5, t_model, t_eq5 - t_article, t_model - t_article, local_alpha_um]
    )
    header = (
        "z_nm,T_article_K,T_eq5_K,T_model_K,"
        "eq5_minus_article_K,model_minus_article_K,local_alpha_eff_um^-1"
    )
    np.savetxt(path, data, delimiter=",", header=header, comments="")
    print(f"Saved {path.resolve()}")


def write_time_profiles_csv(
    path: Path,
    z_nm: np.ndarray,
    t_article: np.ndarray,
    profiles: dict[float, np.ndarray],
) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    columns = [z_nm, t_article]
    names = ["z_nm", "T_article_K"]
    for time_ns, profile in profiles.items():
        columns.append(profile)
        names.append(f"T_model_{time_ns:g}_ns_K")
        columns.append(profile - t_article)
        names.append(f"model_minus_article_{time_ns:g}_ns_K")
    np.savetxt(
        path,
        np.column_stack(columns),
        delimiter=",",
        header=",".join(names),
        comments="",
    )
    print(f"Saved {path.resolve()}")


def write_lateral_profiles_csv(
    path: Path,
    r_um: np.ndarray,
    t_article: np.ndarray,
    t_eq5: np.ndarray,
    profiles: dict[float, np.ndarray],
) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    columns = [r_um, t_article, t_eq5, t_eq5 - t_article]
    names = ["r_um", "T_article_K", "T_eq5_K", "eq5_minus_article_K"]
    for time_ns, profile in profiles.items():
        columns.append(profile)
        names.append(f"T_model_{time_ns:g}_ns_K")
        columns.append(profile - t_article)
        names.append(f"model_minus_article_{time_ns:g}_ns_K")
    np.savetxt(
        path,
        np.column_stack(columns),
        delimiter=",",
        header=",".join(names),
        comments="",
    )
    print(f"Saved {path.resolve()}")


def load_two_column_points(
    path: Path | None,
    *,
    coordinate_name: str,
    temperature_column: str,
) -> np.ndarray:
    if path is None:
        raise SystemExit(f"{coordinate_name} profile CSV path is required")
    if not path.exists():
        raise SystemExit(
            f"{coordinate_name} profile CSV not found: {path}\n"
            "Run digitize_article_temperature_profiles.py first, or pass the correct CSV path."
        )
    with path.open("r", encoding="utf-8") as handle:
        first_line = handle.readline().strip()
    header = [part.strip() for part in first_line.split(",")]
    has_named_columns = coordinate_name in header and temperature_column in header
    if has_named_columns:
        coordinate_index = header.index(coordinate_name)
        temperature_index = header.index(temperature_column)
        data = np.loadtxt(path, delimiter=",", skiprows=1)
    else:
        coordinate_index = 0
        temperature_index = 1
        try:
            data = np.loadtxt(path, delimiter=",", comments="#")
        except ValueError:
            data = np.loadtxt(path, delimiter=",", comments="#", skiprows=1)
    data = np.asarray(data, dtype=float)
    if data.ndim == 1:
        data = data[None, :]
    required_columns = max(coordinate_index, temperature_index) + 1
    if data.ndim != 2 or data.shape[1] < required_columns:
        raise SystemExit(
            f"{path} must contain {coordinate_name} and {temperature_column} columns "
            "or at least two numeric columns"
        )
    points = data[:, [coordinate_index, temperature_index]]
    order = np.argsort(points[:, 0])
    return points[order]


def load_article_temperature_points(
    path: Path | None,
    *,
    coordinate_name: str,
    corrected_temperature_column: str,
    raw_temperature_column: str,
) -> tuple[np.ndarray, np.ndarray, np.ndarray | None]:
    """Load corrected and raw article profiles from one digitized CSV.

    Returns ``coordinate, corrected_temperature, raw_temperature``.  If the
    file is an old two-column profile, raw_temperature is returned as None.
    """
    corrected = load_two_column_points(
        path,
        coordinate_name=coordinate_name,
        temperature_column=corrected_temperature_column,
    )
    try:
        raw = load_two_column_points(
            path,
            coordinate_name=coordinate_name,
            temperature_column=raw_temperature_column,
        )
    except SystemExit:
        return corrected[:, 0], corrected[:, 1], None
    if raw.shape != corrected.shape or not np.allclose(raw[:, 0], corrected[:, 0]):
        raw_values = np.interp(corrected[:, 0], raw[:, 0], raw[:, 1])
    else:
        raw_values = raw[:, 1]
    return corrected[:, 0], corrected[:, 1], raw_values


def main() -> None:
    args = parse_args()

    z_nm, t_article, t_article_raw = load_article_temperature_points(
        args.article_csv,
        coordinate_name="z_nm",
        corrected_temperature_column=args.article_corrected_temperature_column,
        raw_temperature_column=args.article_raw_temperature_column,
    )
    r_lateral_um, t_article_lateral, t_article_lateral_raw = load_article_temperature_points(
        args.article_lateral_csv,
        coordinate_name="r_um",
        corrected_temperature_column=args.article_corrected_temperature_column,
        raw_temperature_column=args.article_raw_temperature_column,
    )
    times_ns = parse_times_ns(args.times_ns)
    if 0.0 not in times_ns:
        times_ns = [0.0] + times_ns
    z_m = z_nm * 1e-9
    r_lateral_m = r_lateral_um * 1e-6
    lateral_z_m = args.lateral_z_nm * 1e-9
    r_plot_um = np.arange(
        np.min(r_lateral_um),
        np.max(r_lateral_um) + 0.5 * args.plot_r_step_um,
        args.plot_r_step_um,
    )
    r_plot_m = r_plot_um * 1e-6

    gst = replace(
        GST225(),
        alpha_linear=args.alpha_linear_um * 1e6,
        alpha_eff=args.alpha_eff_um * 1e6,
    )
    pulse = LaserPulse(
        energy=args.energy_nj * 1e-9,
        radius_1e2=args.beam_radius_um * 1e-6,
    )

    t_eq5 = eq5_temperature(
        z_m,
        gst=gst,
        pulse=pulse,
        ambient_k=args.ambient_k,
        alpha_eff_1_per_m=args.alpha_eff_um * 1e6,
    )
    time_profiles = model_centerline_temperature_profiles(
        z_m,
        times_ns,
        gst=gst,
        pulse=pulse,
        film_thickness_m=args.film_nm * 1e-9,
        ambient_k=args.ambient_k,
        include_phase_change=not args.no_phase_change,
        dt_ns=args.cooling_dt_ns,
    )
    t_model = time_profiles[0.0]
    t_eq5_lateral_plot = eq5_lateral_temperature(
        r_plot_m,
        z_m=lateral_z_m,
        gst=gst,
        pulse=pulse,
        ambient_k=args.ambient_k,
        alpha_eff_1_per_m=args.alpha_eff_um * 1e6,
    )
    lateral_profiles_plot = model_lateral_temperature_profiles(
        r_plot_m,
        times_ns,
        z_m=lateral_z_m,
        gst=gst,
        pulse=pulse,
        film_thickness_m=args.film_nm * 1e-9,
        ambient_k=args.ambient_k,
        include_phase_change=not args.no_phase_change,
        dt_ns=args.cooling_dt_ns,
        radial_extent_m=args.radial_extent_um * 1e-6,
        dr_m=args.dr_um * 1e-6,
    )
    t_eq5_lateral = np.interp(r_lateral_um, r_plot_um, t_eq5_lateral_plot)
    lateral_profiles = {
        time_ns: np.interp(r_lateral_um, r_plot_um, profile)
        for time_ns, profile in lateral_profiles_plot.items()
    }
    local_alpha_um = local_alpha_eff_estimates_um(z_m, t_article, ambient_k=args.ambient_k)

    fitted_alpha_um = None
    fitted_curve = None
    if args.fit_alpha_eff:
        fitted_alpha_um = fit_alpha_eff_um(
            z_m,
            t_article,
            gst=gst,
            pulse=pulse,
            ambient_k=args.ambient_k,
        )
        fitted_curve = eq5_temperature(
            z_m,
            gst=gst,
            pulse=pulse,
            ambient_k=args.ambient_k,
            alpha_eff_1_per_m=fitted_alpha_um * 1e6,
        )

    print("\nCenter-line comparison at r=0")
    print(f"energy = {args.energy_nj:g} nJ, beam radius = {args.beam_radius_um:g} um")
    print(f"alpha_linear = {args.alpha_linear_um:g} um^-1")
    print(f"alpha_eff used = {args.alpha_eff_um:g} um^-1")
    if fitted_alpha_um is not None:
        print(f"least-squares Eq.5 alpha_eff = {fitted_alpha_um:.3g} um^-1")
    print("\nz_nm  T_article  T_eq5  T_model  local_alpha_eff")
    for zn, ta, te, tm, al in zip(z_nm, t_article, t_eq5, t_model, local_alpha_um):
        al_text = "nan" if np.isnan(al) else f"{al:6.2f}"
        print(f"{zn:5.1f} {ta:10.1f} {te:7.1f} {tm:8.1f} {al_text}")

    write_csv(args.csv, z_nm, t_article, t_eq5, t_model, local_alpha_um)
    write_time_profiles_csv(
        args.csv.with_name(args.csv.stem + "_time_profiles.csv"),
        z_nm,
        t_article,
        time_profiles,
    )
    write_lateral_profiles_csv(
        args.csv.with_name(args.csv.stem + "_lateral_profiles.csv"),
        r_lateral_um,
        t_article_lateral,
        t_eq5_lateral,
        lateral_profiles,
    )

    fig, (ax, ax_r) = plt.subplots(1, 2, figsize=(12.0, 5.0))
    if t_article_raw is not None:
        ax.plot(
            t_article_raw,
            z_nm,
            "o",
            color="0.65",
            markerfacecolor="none",
            label="article Fig.4b raw RGB points",
        )
    ax.plot(t_article, z_nm, "ko", label="article Fig.4b corrected points")
    ax.plot(t_eq5, z_nm, "-", label=f"Eq.5, alpha_eff={args.alpha_eff_um:g} um$^{{-1}}$")
    for time_ns, profile in time_profiles.items():
        ax.plot(
            profile,
            z_nm,
            "--",
            label=f"model {time_ns:g} ns"
            + (" no latent" if args.no_phase_change else " latent"),
        )
    if fitted_curve is not None and fitted_alpha_um is not None:
        ax.plot(
            fitted_curve,
            z_nm,
            ":",
            linewidth=2.5,
            label=f"Eq.5 fitted alpha_eff={fitted_alpha_um:.2g} um$^{{-1}}$",
        )
    ax.set_xlabel("Temperature, K")
    ax.set_ylabel("z in GST, nm")
    ax.set_title("Center-line pulse-end temperature profile")
    ax.invert_yaxis()
    ax.grid(True, alpha=0.3)
    ax.legend()

    if t_article_lateral_raw is not None:
        ax_r.plot(
            r_lateral_um,
            t_article_lateral_raw,
            "o",
            color="0.65",
            markerfacecolor="none",
            label="article Fig.4b raw RGB points",
        )
    ax_r.plot(r_lateral_um, t_article_lateral, "ko", label="article Fig.4b corrected points")
    ax_r.plot(
        r_plot_um,
        t_eq5_lateral_plot,
        "-",
        label=f"Eq.5 at z={args.lateral_z_nm:g} nm",
    )
    for time_ns, profile in lateral_profiles_plot.items():
        ax_r.plot(
            r_plot_um,
            profile,
            "--",
            label=f"model {time_ns:g} ns"
            + (" no latent" if args.no_phase_change else " latent"),
        )
    ax_r.set_xlabel("r, um")
    ax_r.set_ylabel("Temperature, K")
    ax_r.set_title(f"Lateral profile at z={args.lateral_z_nm:g} nm")
    ax_r.grid(True, alpha=0.3)
    ax_r.legend()
    fig.tight_layout()
    savefig_overwrite(fig, args.output, dpi=180)


if __name__ == "__main__":
    main()
